# site name
prefixName: 0818x1110の
siteName: 养老基地
# favicon and site master avatar
favicon: /images/favicon.ico
avatar: /images/avatar.jpg
url: /zhangzhongwang-una.github.io
description: 记录爱情&记录生活
#cdn: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6
pjax: 1
# 1开启
mathjax: 0
oss: 'http://una-love.oss-cn-beijing.aliyuncs.com/blog/'

notice: 把我的快乐共享给屏幕前的你们
lazyloadImg: /images/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake }
  # 告白: { path: /confession, fa: fa-film faa-vertical }
  # 清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
  #   番组: {path: /bangumi/, fa: fa-film faa-vertical }, 
  #   歌单: {path: /music/, fa: fa-headphones }
  # } }
  相册: {path: /photos, fa: fa-photo }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  100件事: {path: /100-things, fa: fa-envelope-o }
  # 友人帐: { path: /links/, fa: fa-link faa-shake }
  # 赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  爱情长跑线: {path: /timeline, fa: fa-link faa-shake}
  # 电影: {path: /movies, fa: fa-link faa-shake}
  # 关于: { path: /about, fa: fa-leaf faa-wrench }
  #   , submenus: { 
  # #   我？: {path: /about/, fa: fa-meetup},
  # #  Lab: {path: /lab/, fa: fa-cogs },
  # } }
  # 客户端: { path: /client/, fa: fa-android faa-vertical }
  # RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  # - http://una-love.oss-cn-beijing.aliyuncs.com/blog/yourname1.jpg
  - https://una-love.oss-cn-beijing.aliyuncs.com/figured/20210108120442.png
  # - https://una-love.oss-cn-beijing.aliyuncs.com/figured/A我觉得好图2.jpg
  # - https://una-love.oss-cn-beijing.aliyuncs.com/figured/fengmian.jpg
  # - https://una-love.oss-cn-beijing.aliyuncs.com/figured/截图2.jpg
  # - https://una-love.oss-cn-beijing.aliyuncs.com/figured/合照15.jpg

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: 

# startdash url, title, desc img
startdash: 
  - {url: /, title: left, desc: 左 1 2, img: /images/we/sonoftheweather.jpg}
  #- {url: http://space.bilibili.com/271849279, title: Bilibili, desc: 博主的b站视频, img: /img/startdash/bilibili.jpg}
  - {url: /, title: middle, desc: 中, img: /images/we/sonoftheweather.jpg}
  - {url: /, title: right, desc: 右, img: /images/we/sonoftheweather.jpg}



# your site build time or founded date
siteBuildingTime: 01/01/2020

#social  url, img PC端配置
social:
  github: {url: http://github.com/ZhangZhongWang-Una, img: /images/social/github.png}
  sina: {url: https://weibo.com/u/1849749645?is_all=1, img: /images/social/sina.png}
  netease: {url: https://music.163.com/#/user/home?id=511730579, img: /images/social/wangyiyun.png}
  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=1248001691&site=qq&menu=yes, img: /images/social/qq.png}
  taptap: {url: https://www.taptap.com/user/16248814, img: /images/social/taptap.png}
  wechat: {url: javascript:;, qrcode: /images/social/wechat.jpg, img: /images/social/wechat.png}

#social  url, img 移动端配置
msocial:
  github: {url: http://github.com/ZhangZhongWang-Una, fa: fa-github, color: 333}
  weibo: {url: https://weibo.com/u/1849749645?is_all=1, fa: fa-weibo, color: dd4b39}
  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=1248001691&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

# donate:
#   alipay: /images/donate/AliPayQR.png
#   wechat: /images/donate/WeChatQR.png
#   qqpay: /images/donate/QqPay.png
  
# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
# movies:
#   url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
#   # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
#   name: Unbroken.mp4

aplayer: 
  #id: 2660651585
  id: 5471980240
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine: 
  enable: true
  appId: C1HIie3isYzLvrWHW1k1CfTE-gzGzoHsz
  appKey: PSLCzYDGfVJXcXfsLiUARac0
  notify: false #评论mail回复提醒
  verify: false #验证码
  visitor: false #统计阅读量
  avatar: robohash # Gravatar style : mp/identicon/monsterid/wavatar/retro/hide
  guest_info: nick #,mail,link # custom comment header
  pageSize: 10
  palaceholder: 你是我一生只会遇见一次的惊喜 # Comment Box placeholder

# 前50字描述
post_description:
  enable: true

#评分
widgetpack:
  enable: true #false
  id: 23889 #<app_id>
  color:  fc6423

# busuanzi(http://busuanzi.ibruce.info/) website statistics
# 不蒜子(http://busuanzi.ibruce.info/) 网站统计
busuanziStatistics:
  enable: true
  totalTraffic: true # 总访问量
  totalNumberOfvisitors: false # 总人次

# 是否开启字数统计 (可以在post设置no_word_count: true)
#不需要使用，直接设置值为false，或注释掉
word_count: true
