prefixName: 0818x1110の
siteName: 养老基地
favicon: /img/custom/favicon.ico
avatar: /img/custom/avatar.jpg
url: https://pensionbase.cn/
description: 记录爱情&记录生活
cdn: https://cdn.jsdelivr.net/gh/ZhangZhongWang-Una/CDN@1.0
pjax: 1
# 1开启
mathjax: 0
oss: https://una-love.oss-cn-beijing.aliyuncs.com/blog/

notice: 把我的快乐共享给屏幕前的你们
lazyloadImg: /img/loader/orange.square-circle-preloader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake }
  生活: { path: javascript:;, fa: fa-file-text-o faa-shake, submenus: {
    相册: {path: /photos, fa: fa-photo faa-shake},
    电影: {path: /movie, fa: fa-film faa-shake},
    追剧: {path: /, fa: fa-television faa-shake}
  }}
  表白: {path: /confession, fa: fa-heart faa-shake}
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  100件事: {path: /100-things, fa: fa-envelope-o faa-shake}
  爱情长跑线: {path: /timeline, fa: fa-link faa-shake}

# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - https://una-love.oss-cn-beijing.aliyuncs.com/figured/fengmian.jpg
  # - https://una-love.oss-cn-beijing.aliyuncs.com/blog/picwall/picwall_6.jpg
  # - https://una-love.oss-cn-beijing.aliyuncs.com/blog/picwall/picwall_8.jpg
  # - https://una-love.oss-cn-beijing.aliyuncs.com/blog/picwall/picwall_9.jpg

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: 

# startdash url, title, desc img
startdash: 
  - {url: /, title: 待完成, desc: 未完待续, img: https://una-love.oss-cn-beijing.aliyuncs.com/figured/2021020701.jpg}
  - {url: /, title: 待完成, desc: 未完待续, img: https://una-love.oss-cn-beijing.aliyuncs.com/figured/2021020701.jpg}
  - {url: /, title: 待完成, desc: 未完待续, img: https://una-love.oss-cn-beijing.aliyuncs.com/figured/2021020701.jpg}



# your site build time or founded date
inLoveTime: 11/11/2016 00:00:00

#social  url, img PC端配置
social:
  sina: {url: https://weibo.com/u/1849749645?is_all=1, img: /img/social/sina.png}
  github: {url: https://github.com/ZhangZhongWang-Una, img: /img/social/github.png}
  netease: {url: https://music.163.com/#/user/home?id=511730579, img: /img/social/wangyiyun.png}
  # qq: {url: https://wpa.qq.com/msgrd?v=3&uin=1248001691&site=qq&menu=yes, img: /img/social/qq1.png}
  # taptap: {url: https://www.taptap.com/user/16248814, img: /img/social/taptap.png}
  csdn: {url: https://blog.csdn.net/zzw1248001691, img: /img/social/csdn.png}
  wechat: {url: javascript:;, qrcode: /img/social/wechat.jpg, img: /img/social/wechat.png}

#social  url, img 移动端配置
msocial:
  github: {url: https://github.com/ZhangZhongWang-Una, fa: fa-github, color: 333}
  weibo: {url: https://weibo.com/u/1849749645?is_all=1, fa: fa-weibo, color: dd4b39}
  netease: {url: https://music.163.com/#/user/home?id=511730579, fa: fa-music, color: 25c6fe}
  # qq: {url: https://wpa.qq.com/msgrd?v=3&uin=1248001691&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}
  
# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
# movies:
#   url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
#   # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
#   name: Unbroken.mp4

aplayer: 
  #id: 2660651585
  id: 5471980240
  server: netease
  type: playlist
  fixed: true
  autoplay: true
  loop: all
  order: list
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine: 
  enable: true
  appId: C1HIie3isYzLvrWHW1k1CfTE-gzGzoHsz
  appKey: PSLCzYDGfVJXcXfsLiUARac0
  notify: false #评论mail回复提醒
  verify: false #验证码
  visitor: false #统计阅读量
  avatar: robohash # Gravatar style : mp/identicon/monsterid/wavatar/retro/hide
  guest_info: nick #,mail,link # custom comment header
  pageSize: 10
  palaceholder: 你是我一生只会遇见一次的惊喜 # Comment Box placeholder

# 前50字描述
post_description:
  enable: true

#评分
widgetpack:
  enable: false
  id: 23889
  color:  fc6423

# busuanzi(https://busuanzi.ibruce.info/) website statistics
busuanziStatistics:
  enable: true
  totalTraffic: true # 总访问量
  totalNumberOfvisitors: false # 总人次

# 是否开启字数统计 (可以在post设置no_word_count: true)
word_count: true

# 文章加密
encrypt:
  enable: true
  abstract: 这是一篇加密文章，内容可能是个人情感宣泄或者收费技术。
  message: 请输入文章作者真名缩写查看此文章
  wrong_pass_message: 密码错误，是真名小写缩写，例如zzw!

